const DB_KEY='vrs_admin_db_v2';
const SESSION_KEY='vrs_admin_logged_in';
const AUTH_KEY='vrs_admin_auth_v1';
const DEFAULT_AUTH={username:'vrs@6849',password:'Vrs@123'};

const defaultContent={
  site:{brand:'VENKATESWARAA',footer:'© 2026 Sree Venkateswaraa Regular Service. All Rights Reserved.',phone:'+91 6382210003',email:'info@venkateswaraa.com',address:'Salem, Tamil Nadu',whatsapp:'916382210003',nav:{home:'Home',about:'About',branches:'Branches',services:'Services',track:'Track Order',contact:'Contact',admin:'Admin'}},
  home:{welcome:'Welcome To',name:'Venkatasalam G',role:'Founder & Managing Director',intro:'I founded Sree Venkateswaraa Regular Service in 2018 with one vision—not just to build a company, but to build trust, create opportunities, and leave behind a legacy of excellence.',heroImage:'images/founder/founder.png',knowText:'Know More',knowLink:'about.html',contactText:'Contact Us',contactLink:'contact.html',ctaTitle:'Where Others Stop,',ctaHighlight:'We Deliver.',ctaDescription:'Your trusted partner in manpower & facility management.',ctaButton:'Get Started',ctaLink:'contact.html'},
  about:{title:'About Company',subtitle:'Building Trust Since 2018',company:'Sree Venkateswaraa Regular Service',paragraph1:'We provide professional manpower, facility management, housekeeping, industrial support, and security solutions across Tamil Nadu with a commitment to quality and reliability.',paragraph2:'Our mission is to deliver excellence through skilled manpower, disciplined execution, and customer satisfaction.',stats:[['20+','Years Experience'],['10+','Employees'],['100+','Clients'],['100%','Commitment']]},
  contact:{title:'Contact Us',subtitle:"Let's Build Together",officeTitle:'Office Information',address:'Salem, Tamil Nadu',phone:'+91 6382210003',email:'info@venkateswaraa.com',button:'View All Office Details'},
  services:{title:'Our Delivery Locations',subtitle:'Places covered across Salem, Dharmapuri and Krishnagiri districts',note:'Delivery may be available, or shipments can be transferred to connecting transport services.'},
  track:{title:'Track Your Order',subtitle:'Enter your Order ID below.',assignedTeam:'Operations Team',completion:'Within 24 Hours'},
  partners:[
    {name:'Partner 1',image:'images/partners/partner-1.png'},
    {name:'Partner 2',image:'images/partners/partner-2.png'},
    {name:'Partner 3',image:'images/partners/partner-3.png'},
    {name:'Partner 4',image:'images/partners/partner-4.png'},
    {name:'Partner 5',image:'images/partners/partner-5.png'},
    {name:'Partner 6',image:'images/partners/partner-6.png'}
  ],
  theme:{gold:'#d4af37',background:'#111111',card:'#1a1a1a',text:'#ffffff',muted:'#bbbbbb'}
};

const seedBranches=[
 {id:'BR-DHARMAPURI',name:'Dharmapuri Office (Head Office)',city:'Dharmapuri',phone:'+91 6381847231',address:'RC RiceMill, 47, Dharmapuri - Pennagaram Main Rd, Kumarasamypettai, Dharmapuri, Tamil Nadu - 636701',email:'dharmapuri@venkateswaraa.com',map:'https://maps.google.com/'},
 {id:'BR-SALEM',name:'Salem Office',city:'Salem',phone:'+91 63822 10003',address:'M524+CJQ, Riverside Road, Agraharam, Salem, Tamil Nadu - 636001',email:'salem@venkateswaraa.com',map:'https://maps.google.com/'},
 {id:'BR-HOSUR',name:'Hosur Office',city:'Hosur',phone:'+91 97869 57249',address:'78, Junction Main Road, Hosur, Tamil Nadu - 636004',email:'hosur@venkateswaraa.com',map:'https://maps.google.com/'}
];

const seedLocations=[
 ['Salem','Salem Head Office','636001'],['Salem','Salem Bazaar','636002'],['Salem','Shevapet','636002'],['Salem','Suramangalam / Salem Junction','636005'],['Salem','Hasthampatti','636007'],['Salem','Ammapet','636003'],['Salem','Fairlands','636004'],['Salem','Kondalampatti','636010'],['Salem','Meyyanur','636004'],['Salem','Alagapuram','636016'],['Salem','Kannankurichi','636008'],['Salem','Junction Main Road','636005'],['Salem','Five Roads','636004'],['Salem','Swarnapuri','636016'],['Salem','Seelanaickenpatti','636201'],['Salem','Kumarasamypatti','636007'],['Salem','Gugai','636006'],['Salem','Dadagapatti','636006'],['Salem','Kitchipalayam','636015'],['Salem','Ponnammapet','636001'],['Salem','Sankari','637301'],['Salem','Edappadi','637101'],['Salem','Mettur','636401'],['Salem','Omalur','636455'],['Salem','Attur','636102'],['Salem','Vazhapadi','636115'],['Salem','Thammampatti','636113'],['Salem','Gangavalli','636105'],['Salem','Yercaud','636601'],['Salem','Ayothiapattinam','636103'],['Salem','Mallur','636203'],['Salem','Rasipuram','637408'],['Salem','Namakkal Road','637001'],['Salem','Veerapandi','637308'],['Salem','Magudanchavadi','637103'],['Salem','Mettur Dam','636403'],['Salem','Kolathur','636303'],['Salem','Mecheri','636453'],['Salem','Nangavalli','636454'],['Salem','Tharamangalam','636502'],['Salem','Jalagamparai','636455'],['Salem','Konganapuram','637102'],
 ['Dharmapuri','Dharmapuri Head Office','636701'],['Dharmapuri','Collectorate / Vennampatti','636705'],['Dharmapuri','Annasagaram','636704'],['Dharmapuri','Adiyamankottai','636807'],['Dharmapuri','Indur','636803'],['Dharmapuri','Paupparapatti / Sogathur','636809'],['Dharmapuri','Palacode (Palakkodu)','636808'],['Dharmapuri','Marandahalli','636806'],['Dharmapuri','Karimangalam','635111'],['Dharmapuri','Kambainallur','635202'],['Dharmapuri','Harur','636903'],['Dharmapuri','Pennagaram','636810'],['Dharmapuri','Hogenakkal','636810'],['Dharmapuri','Nallampalli','636807'],['Dharmapuri','Bommidi','635301'],['Dharmapuri','Pappireddipatti','636905'],['Dharmapuri','Kadathur','635303'],['Dharmapuri','Kottapatti','636704'],['Dharmapuri','Eriyur','636810'],['Dharmapuri','Mottankurichi','636803'],['Dharmapuri','Kaveripattinam','635112'],['Dharmapuri','Pennagaram Road','636810'],['Dharmapuri','B. Pallipatti','636809'],['Dharmapuri','Morappur','635305'],['Dharmapuri','Neruppur','636803'],
 ['Krishnagiri','Krishnagiri Head Office','635001'],['Krishnagiri','Krishnagiri Collectorate / Polupalli','635115'],['Krishnagiri','Kattiganapalli','635002'],['Krishnagiri','Kaveripattinam','635112'],['Krishnagiri','Bargur','635104'],['Krishnagiri','Natrampalli','635852'],['Krishnagiri','Jolarpet','635851'],['Krishnagiri','Vaniyambadi Road','635751'],['Krishnagiri','Pochampalli','635206'],['Krishnagiri','Barur','635201'],['Krishnagiri','Mathur','635203'],['Krishnagiri','Nagarasampatti','635204'],['Krishnagiri','Uthangarai','635207'],['Krishnagiri','Singarapettai','635307'],['Krishnagiri','Samalpatti','635306'],['Krishnagiri','Kallavi','635304'],['Krishnagiri','Hosur Head Office','635109'],['Krishnagiri','Hosur Industrial Complex / Sipcot','635126'],['Krishnagiri','Mookandapalli','635126'],['Krishnagiri','Bagalur','635103'],['Krishnagiri','Mathigiri','635110'],['Krishnagiri','Zuzuvadi','635126'],['Krishnagiri','Moranapalli','635109'],['Krishnagiri','Alasanatham','635109'],['Krishnagiri','Berigai','635105'],['Krishnagiri','Shoolagiri','635117'],['Krishnagiri','Uddanapalli','635119'],['Krishnagiri','Kamandoddi','635109'],['Krishnagiri','Denkanikottai','635107'],['Krishnagiri','Kelamangalam','635113'],['Krishnagiri','Thally','635118'],['Krishnagiri','Anchetti','636815'],['Krishnagiri','Urigam','635102'],['Krishnagiri','Jawalagiri','635118']
].map((x,i)=>({id:'LOC-'+String(i+1).padStart(3,'0'),city:x[0],area:x[1],pin:x[2],status:'Active'}));

const defaultDB={orders:[],customers:[],branches:seedBranches,locations:seedLocations,content:defaultContent};
let db=loadDB();
let currentEntity='';
let editingId=null;

function clone(o){return JSON.parse(JSON.stringify(o))}
function mergeContent(saved){const c=clone(defaultContent);if(!saved)return c;for(const k of Object.keys(saved)){if(k==='site'&&saved.site)c.site={...c.site,...saved.site,nav:{...c.site.nav,...(saved.site.nav||{})}};else if(k==='home'&&saved.home)c.home={...c.home,...saved.home};else if(k==='about'&&saved.about)c.about={...c.about,...saved.about,stats:saved.about.stats||c.about.stats};else if(k==='contact'&&saved.contact)c.contact={...c.contact,...saved.contact};else if(k==='services'&&saved.services)c.services={...c.services,...saved.services};else if(k==='track'&&saved.track)c.track={...c.track,...saved.track};else if(k==='theme'&&saved.theme)c.theme={...c.theme,...saved.theme};else if(k==='partners'&&Array.isArray(saved.partners))c.partners=saved.partners;}return c}
function loadDB(){try{const raw=JSON.parse(localStorage.getItem(DB_KEY)||'{}');const data={...defaultDB,...raw};data.content=mergeContent(raw.content);if(!Array.isArray(data.branches)||!data.branches.length)data.branches=clone(seedBranches);if(!Array.isArray(data.locations)||!data.locations.length)data.locations=clone(seedLocations);localStorage.setItem(DB_KEY,JSON.stringify(data));return data}catch(e){return clone(defaultDB)}}
function saveDB(){localStorage.setItem(DB_KEY,JSON.stringify(db));renderAll();fillContentEditor();toast('Saved successfully')}
function id(prefix){return prefix+'-'+Date.now().toString(36).toUpperCase()+Math.floor(Math.random()*90+10)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function status(v){return `<span class="status ${esc(v)}">${esc(v)}</span>`}
function emptyRow(cols,msg='No records found.'){return `<tr><td class="empty" colspan="${cols}">${msg}</td></tr>`}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function query(id){return document.getElementById(id).value.toLowerCase().trim()}
function renderAll(){document.getElementById('statOrders').textContent=db.orders.length;document.getElementById('statCustomers').textContent=db.customers.length;document.getElementById('statBranches').textContent=db.branches.length;document.getElementById('statLocations').textContent=db.locations.filter(x=>x.status==='Active').length;renderOrders();renderCustomers();renderBranches();renderLocations();renderRecent();}
function renderRecent(){const rows=db.orders.slice(-5).reverse();document.getElementById('recentOrders').innerHTML=rows.length?rows.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.customer)}</td><td>${esc(o.from)}</td><td>${esc(o.to)}</td><td>${status(o.status)}</td></tr>`).join(''):emptyRow(5,'No orders yet.')}
function renderOrders(){const q=query('ordersSearch');const rows=db.orders.filter(o=>Object.values(o).join(' ').toLowerCase().includes(q));document.getElementById('ordersTable').innerHTML=rows.length?rows.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.customer)}</td><td>${esc(o.phone)}</td><td>${esc(o.from)}</td><td>${esc(o.to)}</td><td>${esc(o.package)}</td><td>${status(o.status)}</td><td class="actions"><button class="icon-btn edit" onclick="openEdit('orders','${o.id}')">Edit</button><button class="icon-btn delete" onclick="removeRecord('orders','${o.id}')">Delete</button></td></tr>`).join(''):emptyRow(8)}
function renderCustomers(){const q=query('customersSearch');const rows=db.customers.filter(o=>Object.values(o).join(' ').toLowerCase().includes(q));document.getElementById('customersTable').innerHTML=rows.length?rows.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.name)}</td><td>${esc(o.phone)}</td><td>${esc(o.email)}</td><td>${esc(o.city)}</td><td class="actions"><button class="icon-btn edit" onclick="openEdit('customers','${o.id}')">Edit</button><button class="icon-btn delete" onclick="removeRecord('customers','${o.id}')">Delete</button></td></tr>`).join(''):emptyRow(6)}
function renderBranches(){const q=query('branchesSearch');const rows=db.branches.filter(o=>Object.values(o).join(' ').toLowerCase().includes(q));document.getElementById('branchesTable').innerHTML=rows.length?rows.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.name)}</td><td>${esc(o.city)}</td><td>${esc(o.phone)}</td><td>${esc(o.address)}</td><td class="actions"><button class="icon-btn edit" onclick="openEdit('branches','${o.id}')">Edit</button><button class="icon-btn delete" onclick="removeRecord('branches','${o.id}')">Delete</button></td></tr>`).join(''):emptyRow(6)}
function renderLocations(){const q=query('locationsSearch');const rows=db.locations.filter(o=>Object.values(o).join(' ').toLowerCase().includes(q));document.getElementById('locationsTable').innerHTML=rows.length?rows.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.area)}</td><td>${esc(o.city)}</td><td>${esc(o.pin)}</td><td>${status(o.status)}</td><td class="actions"><button class="icon-btn edit" onclick="openEdit('locations','${o.id}')">Edit</button><button class="icon-btn delete" onclick="removeRecord('locations','${o.id}')">Delete</button></td></tr>`).join(''):emptyRow(6)}

const schemas={orders:[['customer','Customer Name','text',true],['phone','Phone','tel',true],['from','From Location','text',true],['to','To Location','text',true],['package','Package Details','text',true],['status','Status','select',true,['Pending','Processing','Delivered','Cancelled']],['notes','Notes','textarea',false]],customers:[['name','Full Name','text',true],['phone','Phone','tel',true],['email','Email','email',true],['city','City','text',true]],branches:[['name','Branch Name','text',true],['city','City','text',true],['phone','Phone','tel',true],['email','Email','email',false],['address','Address','textarea',true],['map','Google Maps URL','url',false]],locations:[['area','Area / Locality','text',true],['city','District / City','text',true],['pin','PIN Code','text',true],['status','Status','select',true,['Active','Inactive']]]};
function openCreate(entity){currentEntity=entity;editingId=null;document.getElementById('modalTitle').textContent='Add '+label(entity);buildForm(entity,{});document.getElementById('modal').classList.remove('hidden')}
function openEdit(entity,recordId){const rec=db[entity].find(x=>x.id===recordId);if(!rec)return;currentEntity=entity;editingId=recordId;document.getElementById('modalTitle').textContent='Edit '+label(entity);buildForm(entity,rec);document.getElementById('modal').classList.remove('hidden')}
function label(e){return e==='locations'?'Delivery Location':e.slice(0,-1).replace(/^./,x=>x.toUpperCase())}
function buildForm(entity,rec){document.getElementById('formFields').innerHTML=schemas[entity].map(f=>{const [key,name,type,req,opts]=f;let input;if(type==='select')input=`<select id="field_${key}" ${req?'required':''}>${opts.map(x=>`<option ${rec[key]===x?'selected':''}>${x}</option>`).join('')}</select>`;else if(type==='textarea')input=`<textarea id="field_${key}" ${req?'required':''}>${esc(rec[key]||'')}</textarea>`;else input=`<input id="field_${key}" type="${type}" value="${esc(rec[key]||'')}" ${req?'required':''}>`;return `<div class="form-field ${type==='textarea'?'full':''}"><label for="field_${key}">${name}${req?' *':''}</label>${input}</div>`}).join('')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function removeRecord(entity,recordId){if(!confirm('Delete this record? This action cannot be undone.'))return;db[entity]=db[entity].filter(x=>x.id!==recordId);saveDB();toast('Record deleted')}

function getVal(id){return document.getElementById(id)?.value??''}
function setVal(id,v){const el=document.getElementById(id);if(el)el.value=v??''}
function fillContentEditor(){const c=db.content;setVal('c_brand',c.site.brand);setVal('c_footer',c.site.footer);setVal('c_phone',c.site.phone);setVal('c_email',c.site.email);setVal('c_address',c.site.address);setVal('c_whatsapp',c.site.whatsapp);for(const [k,v] of Object.entries(c.site.nav))setVal('nav_'+k,v);
 [['home_welcome',c.home.welcome],['home_name',c.home.name],['home_role',c.home.role],['home_intro',c.home.intro],['home_image',c.home.heroImage],['home_know',c.home.knowText],['home_knowlink',c.home.knowLink],['home_contact',c.home.contactText],['home_contactlink',c.home.contactLink],['home_ctatitle',c.home.ctaTitle],['home_ctahighlight',c.home.ctaHighlight],['home_ctadesc',c.home.ctaDescription],['home_ctabutton',c.home.ctaButton],['home_ctalink',c.home.ctaLink]].forEach(([i,v])=>setVal(i,v));
 [['about_title',c.about.title],['about_subtitle',c.about.subtitle],['about_company',c.about.company],['about_p1',c.about.paragraph1],['about_p2',c.about.paragraph2]].forEach(([i,v])=>setVal(i,v));
 c.about.stats.forEach((s,i)=>{setVal('stat_num_'+i,s[0]);setVal('stat_label_'+i,s[1])});
 [['contact_title',c.contact.title],['contact_subtitle',c.contact.subtitle],['contact_office',c.contact.officeTitle],['contact_address',c.contact.address],['contact_phone',c.contact.phone],['contact_email',c.contact.email],['contact_button',c.contact.button]].forEach(([i,v])=>setVal(i,v));
 [['services_title',c.services.title],['services_subtitle',c.services.subtitle],['services_note',c.services.note]].forEach(([i,v])=>setVal(i,v));
 [['track_title',c.track.title],['track_subtitle',c.track.subtitle],['track_team',c.track.assignedTeam],['track_completion',c.track.completion]].forEach(([i,v])=>setVal(i,v));
 ['gold','background','card','text','muted'].forEach(k=>setVal('theme_'+k,c.theme[k]));
 c.partners.forEach((p,i)=>{setVal('partner_name_'+i,p.name);setVal('partner_image_'+i,p.image)});
}
function saveWebsite(){const c=clone(db.content);c.site.brand=getVal('c_brand');c.site.footer=getVal('c_footer');c.site.phone=getVal('c_phone');c.site.email=getVal('c_email');c.site.address=getVal('c_address');c.site.whatsapp=getVal('c_whatsapp').replace(/\D/g,'');for(const k of Object.keys(c.site.nav))c.site.nav[k]=getVal('nav_'+k);
 Object.assign(c.home,{welcome:getVal('home_welcome'),name:getVal('home_name'),role:getVal('home_role'),intro:getVal('home_intro'),heroImage:getVal('home_image'),knowText:getVal('home_know'),knowLink:getVal('home_knowlink'),contactText:getVal('home_contact'),contactLink:getVal('home_contactlink'),ctaTitle:getVal('home_ctatitle'),ctaHighlight:getVal('home_ctahighlight'),ctaDescription:getVal('home_ctadesc'),ctaButton:getVal('home_ctabutton'),ctaLink:getVal('home_ctalink')});
 Object.assign(c.about,{title:getVal('about_title'),subtitle:getVal('about_subtitle'),company:getVal('about_company'),paragraph1:getVal('about_p1'),paragraph2:getVal('about_p2')});c.about.stats=[0,1,2,3].map(i=>[getVal('stat_num_'+i),getVal('stat_label_'+i)]);
 Object.assign(c.contact,{title:getVal('contact_title'),subtitle:getVal('contact_subtitle'),officeTitle:getVal('contact_office'),address:getVal('contact_address'),phone:getVal('contact_phone'),email:getVal('contact_email'),button:getVal('contact_button')});Object.assign(c.services,{title:getVal('services_title'),subtitle:getVal('services_subtitle'),note:getVal('services_note')});Object.assign(c.track,{title:getVal('track_title'),subtitle:getVal('track_subtitle'),assignedTeam:getVal('track_team'),completion:getVal('track_completion')});
 for(const k of ['gold','background','card','text','muted'])c.theme[k]=getVal('theme_'+k);c.partners=c.partners.map((p,i)=>({name:getVal('partner_name_'+i),image:getVal('partner_image_'+i)}));db.content=c;saveDB();toast('Website settings saved. Refresh the public website to see changes.')}
function uploadImage(input,target){const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{setVal(target,reader.result);toast('Image loaded. Save Website Settings to keep it.')};reader.readAsDataURL(file)}

// Admin authentication (frontend-only demo)
function getAuth(){try{const saved=JSON.parse(localStorage.getItem(AUTH_KEY)||'null');if(saved&&typeof saved.password==='string'&&saved.password){return {username:DEFAULT_AUTH.username,password:saved.password}}}catch(e){}localStorage.setItem(AUTH_KEY,JSON.stringify(DEFAULT_AUTH));return {...DEFAULT_AUTH}}
function saveAuth(username,password){localStorage.setItem(AUTH_KEY,JSON.stringify({username:DEFAULT_AUTH.username,password}))}
function updateLoginHint(){const a=getAuth();const el=document.getElementById('loginHint');if(el)el.innerHTML='Current login username: <b>'+esc(a.username)+'</b>'}
function updateAdminIdentity(){const a=getAuth();const el=document.getElementById('adminUserName');if(el)el.textContent=a.username}

// Login / app

document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();const u=document.getElementById('loginUsername').value.trim();const p=document.getElementById('loginPassword').value;const a=getAuth();if(u===a.username&&p===a.password){sessionStorage.setItem(SESSION_KEY,'1');document.getElementById('loginError').textContent='';showApp()}else document.getElementById('loginError').textContent='Invalid username or password.'});
function showApp(){document.getElementById('loginScreen').classList.add('hidden');document.getElementById('adminApp').classList.remove('hidden');renderAll();fillContentEditor();updateAdminIdentity()}
updateLoginHint();
if(sessionStorage.getItem(SESSION_KEY)==='1')showApp();
document.getElementById('logoutBtn').onclick=()=>{sessionStorage.removeItem(SESSION_KEY);location.reload()};document.getElementById('closeModal').onclick=closeModal;document.getElementById('cancelModal').onclick=closeModal;document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
document.getElementById('recordForm').addEventListener('submit',e=>{e.preventDefault();const rec={};schemas[currentEntity].forEach(f=>rec[f[0]]=document.getElementById('field_'+f[0]).value.trim());if(editingId){const i=db[currentEntity].findIndex(x=>x.id===editingId);rec.id=editingId;db[currentEntity][i]=rec}else{const prefixes={orders:'ORD',customers:'CUS',branches:'BR',locations:'LOC'};rec.id=id(prefixes[currentEntity]);db[currentEntity].push(rec)}saveDB();closeModal()});
document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>switchSection(btn.dataset.section));document.querySelectorAll('[data-open]').forEach(btn=>btn.onclick=()=>switchSection(btn.dataset.open));function switchSection(section){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.section===section));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active-section'));document.getElementById(section).classList.add('active-section');document.getElementById('pageTitle').textContent=section==='locations'?'Delivery Locations':section==='website'?'Website Management':section[0].toUpperCase()+section.slice(1);document.querySelector('.sidebar').classList.remove('open');if(section==='website')fillContentEditor()}
document.getElementById('addOrderBtn').onclick=()=>openCreate('orders');document.getElementById('addCustomerBtn').onclick=()=>openCreate('customers');document.getElementById('addBranchBtn').onclick=()=>openCreate('branches');document.getElementById('addLocationBtn').onclick=()=>openCreate('locations');['ordersSearch','customersSearch','branchesSearch','locationsSearch'].forEach(x=>document.getElementById(x).addEventListener('input',renderAll));document.getElementById('mobileMenu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.getElementById('saveWebsiteBtn').onclick=saveWebsite;
document.getElementById('credentialsForm').addEventListener('submit',e=>{e.preventDefault();const current=getVal('currentAdminPassword');const password=getVal('newAdminPassword');const confirm=getVal('confirmAdminPassword');const msg=document.getElementById('credentialsMessage');const auth=getAuth();msg.className='editor-help';if(current!==auth.password){msg.textContent='Password change denied: the current password is incorrect.';msg.classList.add('error-text');return}if(password.length<6){msg.textContent='New password must be at least 6 characters.';msg.classList.add('error-text');return}if(password!==confirm){msg.textContent='New password and confirmation do not match.';msg.classList.add('error-text');return}saveAuth(auth.username,password);document.getElementById('credentialsForm').reset();msg.className='editor-help success-text';msg.textContent='Password changed successfully. Your admin username remains unchanged.';toast('Admin password changed')});
document.getElementById('showPasswordBtn').onclick=()=>{const ids=['currentAdminPassword','newAdminPassword','confirmAdminPassword'];const show=document.getElementById('currentAdminPassword').type==='password';ids.forEach(id=>document.getElementById(id).type=show?'text':'password');document.getElementById('showPasswordBtn').textContent=show?'Hide Passwords':'Show Passwords';};
document.querySelectorAll('.image-upload').forEach(i=>i.addEventListener('change',()=>uploadImage(i,i.dataset.target)));
